# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-23 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBS', '0002_ariticlecmmt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AriticleCmmt',
            new_name='ArticleCmmt',
        ),
    ]
